# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Restore Python virtual environment cache
      uses: actions/cache@v2
      id: cache-venv
      with:
        path: ./.venv/
        key: ${{ runner.os }}-virtualenv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-virtualenv-
    - name: Install dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: |
        rm -rf ./.venv
        python -m venv ./.venv
        source ./.venv/bin/activate
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Code inspections with flake8
      run: |
        source ./.venv/bin/activate
        # stop the build if there are Python syntax errors or undefined names
        flake8 tnp_dash_library --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 tnp_dash_library --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Unit tests with pytest
      run: |
        source ./.venv/bin/activate
        python -m pytest tests/
